package cinemacontroller.historicalcontroller;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;

import databasecontroller.MySqlController;


/**
 *
 * @author Frédéric
 */
public class HistoricalExport {

	private ArrayList<String> data = new ArrayList<String>();
	private String date;
	private String folder = "historicals\\";
	
    public HistoricalExport(){

    }

    
    public void createXmlContent(String date){
    	
    	data.clear();
    	this.date = date;
    	
    	String comments = "<!--\n XML file - Historical data from "+date+"\n Generated by Multiplex Manager\n-->\n\n";
    	String header = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\n";
    	String content = "";
    	
        MySqlController connection;
        ResultSet result;

		try {
			
			connection = MySqlController.getInstance();
			//select data between the beginDate and the endDate
			//System.out.println("SELECT * FROM TIMETABLES WHERE DAY<'"+date+"'");
			result= connection.getData("SELECT * FROM TIMETABLES WHERE DAY='"+date+"'");
			content = "<historical>\n\n";
			while (result.next()) {
				
				content += "    <idScreen>"+result.getString(1)+"</idScreen>\n";
				content += "    <idMovie>"+result.getString(2)+"</idMovie>\n";
				content += "    <day>"+result.getString(3)+"</day>\n";
				content += "    <expectedBooking>"+result.getString(4)+"</expectedBooking>\n";
				content += "    <nbSeatsBooked>"+result.getString(5)+"</nbSeatsBooked>\n\n";

			}
			content += "</historical>";
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
    	
		data.add(comments+header+content);
    }
    
    public void writeXmlContent(){
    	
    	BufferedWriter out = null;
    	File file = new File(date+"_Historical.xml");

    	String content = "";
		try {
			
			out = new BufferedWriter(new OutputStreamWriter(
					new FileOutputStream(getPath(file)), "UTF-8"));

			Iterator it = data.iterator();
			while(it.hasNext()){
				content += it.next().toString();
			}
			
			out.write(content);

		}

		catch (UnsupportedEncodingException ue) {

			System.out.println(ue.getMessage());

		}

		catch (IOException e) {

			System.out.println(e.getMessage());

		} finally {
			try {
				out.flush();
				out.close();
			} catch (IOException exception1) {
				exception1.printStackTrace();
			}
		}

	}
    
    
    public void deleteContent(){
    	
        MySqlController connection;

		try {
			
			connection = MySqlController.getInstance();

			//System.out.println("DELETE FROM TIMETABLES WHERE DAY='"+date+"'");
			connection.putData("DELETE FROM TIMETABLES WHERE DAY='"+date+"'");

			
		} catch (SQLException e) {
			e.printStackTrace();
		}
    	
    }
    public String getPath(File file){
    	String path = file.getAbsolutePath().replace(file.toString(), "")+folder+file.toString();
    	return path;
    }
   
}
