/*
 * ImportController.java
 *
 * Created on 31 mars 2009, 12:16
 */

package cinemacontroller.historicalcontroller;

import java.util.Calendar;

import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import usefulmethods.TextLimiter;
import usefulmethods.Useful;

/**
 *
 * @author  Frédéric
 */
public class ImportController extends javax.swing.JFrame {

	private static final long serialVersionUID = -3688656990364226359L;
	private Useful use;
    /** Creates new form ImportController */
    public ImportController() {
    	use = new Useful();
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane_date_description = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        bgroup = new javax.swing.ButtonGroup();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton("",true);
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Import Historical - Multiplex Manager");
        setIconImage(getToolkit().getImage(getClass().getResource("/cinemacontroller/gui/icons/import.png")));

        jPanel2.setBackground(new java.awt.Color(24, 24, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Import Historicals");

        jScrollPane3.setBorder(null);

        jTextPane_date_description.setBackground(new java.awt.Color(24, 24, 24));
        jTextPane_date_description.setEditable(false);
        jTextPane_date_description.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane_date_description.setText("You can import historical data by choosing a specific date or a period.\n");
        jScrollPane3.setViewportView(jTextPane_date_description);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        
        jTextField1.setDocument(new TextLimiter(2));
        jTextField2.setDocument(new TextLimiter(2));
        jTextField3.setDocument(new TextLimiter(4));
        
        jTextField4.setDocument(new TextLimiter(2));
        jTextField5.setDocument(new TextLimiter(2));
        jTextField6.setDocument(new TextLimiter(4));
        
        jTextField7.setDocument(new TextLimiter(2));
        jTextField8.setDocument(new TextLimiter(2));
        jTextField9.setDocument(new TextLimiter(4));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("Import a day");

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel12.setText("Import a day");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("between");

        jLabel3.setText("to");
        
        bgroup.add(jRadioButton1);
        bgroup.add(jRadioButton2);

        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        
        defaultTextField();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addGap(10, 10, 10)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jRadioButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    public void defaultTextField(){
    	jTextField4.setEditable(false);
    	jTextField5.setEditable(false);
    	jTextField6.setEditable(false);
    	jTextField7.setEditable(false);
    	jTextField8.setEditable(false);
    	jTextField9.setEditable(false);
    	
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	Calendar dateEndPeriod = use.getDateEndPeriod();
    	Calendar dateBeginPeriod = (Calendar)dateEndPeriod.clone();
    	dateBeginPeriod = use.changeDate(dateBeginPeriod, -13);
    	
    	//just a day
    	if(jRadioButton1.isSelected()){
    		
    		if(!jTextField1.getText().isEmpty() && !jTextField2.getText().isEmpty() && !jTextField3.getText().isEmpty()){
    			
    			if(jTextField1.getText().length() == 2 && jTextField2.getText().length() == 2 && jTextField3.getText().length() == 4
    					&& jTextField1.getText().matches("[0-9]*") && jTextField2.getText().matches("[0-9]*") && jTextField3.getText().matches("[0-9]*")){
    				
    				String date = jTextField3.getText()+"-"+jTextField2.getText()+"-"+jTextField1.getText();
    				if(date.compareTo(use.calendarToString(dateBeginPeriod)) < 0){
    					this.dispose();
    					new HistoricalWaiting(date,"",0);
    					

    				}
    				else{
    					JOptionPane.showMessageDialog(null, "Please enter a date lower than the period beginning ("+use.calendarToString(dateBeginPeriod)+")", "No Historical", JOptionPane.WARNING_MESSAGE);
    				}
	
    			}
    			else{
    		    	JOptionPane.showMessageDialog(null, "Please enter a correct date.", "Invalid Date", JOptionPane.WARNING_MESSAGE);
    		    }
    			
    			
    		}
    		else{
		    	JOptionPane.showMessageDialog(null, "Please enter a day.", "Invalid Data", JOptionPane.WARNING_MESSAGE);
		    }
    	}
    	else{
    		//a period
    		if(jRadioButton2.isSelected()){

    			if(!jTextField4.getText().isEmpty() && !jTextField5.getText().isEmpty() && !jTextField6.getText().isEmpty()
    				&& !jTextField7.getText().isEmpty() && !jTextField8.getText().isEmpty() && !jTextField9.getText().isEmpty()	){
    				
    				if(jTextField4.getText().length() == 2 && jTextField5.getText().length() == 2 && jTextField6.getText().length() == 4
    					&& jTextField7.getText().length() == 2 && jTextField8.getText().length() == 2 && jTextField9.getText().length() == 4
    					&& jTextField4.getText().matches("[0-9]*") && jTextField5.getText().matches("[0-9]*") && jTextField6.getText().matches("[0-9]*")
    					&& jTextField7.getText().matches("[0-9]*") && jTextField8.getText().matches("[0-9]*") && jTextField9.getText().matches("[0-9]*")){
    					
    					
    					String date1 = jTextField6.getText()+"-"+jTextField5.getText()+"-"+jTextField4.getText();
    					String date2 = jTextField9.getText()+"-"+jTextField8.getText()+"-"+jTextField7.getText();
    					
    					if(date2.compareTo(date1) >= 0){
    						
    						if(date2.compareTo(use.calendarToString(dateBeginPeriod)) < 0){
    							this.dispose();
    							new HistoricalWaiting(date1,date2,1);
    						}
    						else{
            					JOptionPane.showMessageDialog(null, "Please enter a second date is lower than the period beginning ("+use.calendarToString(dateBeginPeriod)+").", "Invalid Date", JOptionPane.WARNING_MESSAGE);
            				}

        				}
    					else{
        					JOptionPane.showMessageDialog(null, "Please enter a second date greater or equals to the first date.", "Invalid Date", JOptionPane.WARNING_MESSAGE);
        				}

    				}
    				else{
        		    	JOptionPane.showMessageDialog(null, "Please enter two days with a correct format.", "Invalid Date", JOptionPane.WARNING_MESSAGE);
        		    }
    				
    			}
        		else{
    		    	JOptionPane.showMessageDialog(null, "Please enter two days.", "Invalid Data", JOptionPane.WARNING_MESSAGE);
    		    }
        	}
    	}

    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    	this.dispose();

    }
    
private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
	
	jTextField1.setEditable(true);
	jTextField2.setEditable(true);
	jTextField3.setEditable(true);
	
	jTextField4.setText("");
	jTextField4.setEditable(false);
	jTextField5.setText("");
	jTextField5.setEditable(false);
	jTextField6.setText("");
	jTextField6.setEditable(false);
	jTextField7.setText("");
	jTextField7.setEditable(false);
	jTextField8.setText("");
	jTextField8.setEditable(false);
	jTextField9.setText("");
	jTextField9.setEditable(false);
	
}

private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
	
	jTextField4.setEditable(true);
	jTextField5.setEditable(true);
	jTextField6.setEditable(true);
	jTextField7.setEditable(true);
	jTextField8.setEditable(true);
	jTextField9.setEditable(true);
	
	jTextField1.setText("");
	jTextField1.setEditable(false);
	jTextField2.setText("");
	jTextField2.setEditable(false);
	jTextField3.setText("");
	jTextField3.setEditable(false);
}


    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.ButtonGroup bgroup;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextPane jTextPane_date_description;
    // End of variables declaration

}
