/*
 * AddUser.java
 *
 * Created on 25 mars 2009, 13:56
 */

package cinemacontroller.gui;

import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;

import usefulmethods.Useful;

import databasecontroller.MySqlController;

/**
 *
 * @author  Frédéric
 */
public class AddUser extends javax.swing.JFrame {

	private static final long serialVersionUID = 0L;
    /** Creates new form AddUser */
    public AddUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane_date_description = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add User - Multiplex Manager");
        setIconImage(getToolkit().getImage(getClass().getResource("/cinemacontroller/gui/icons/user.png")));

        jPanel2.setBackground(new java.awt.Color(24, 24, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Add User");

        jScrollPane3.setBorder(null);

        jTextPane_date_description.setBackground(new java.awt.Color(24, 24, 24));
        jTextPane_date_description.setEditable(false);
        jTextPane_date_description.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane_date_description.setText("This window allows to add a new user into the database. Then the new user could be log in to the application.");
        jScrollPane3.setViewportView(jTextPane_date_description);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("Username");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("Password");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel14.setText("Confirm Password");

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(142, 142, 142))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 234, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
	this.dispose();

}

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
	
	if(!jTextField1.getText().trim().isEmpty()){
		
		if(!new String(jTextField2.getPassword()).trim().isEmpty()){
			
			if(!new String(jTextField5.getPassword()).trim().isEmpty()){
				
				//check if the unsername doesn't exist in the database
    			try {

    	        	MySqlController connection = MySqlController.getInstance();

    	        	ResultSet result = connection.getData("SELECT * FROM accounts WHERE USERNAME = '"+jTextField1.getText().trim()+"'");
    	        	
    	        	//if there is no result
    	            if(!result.next()){
    	            	
    	            	//check the two passwords
    	            	if(new String(jTextField2.getPassword()).trim().equals(new String(jTextField5.getPassword()).trim())){
    	            		
    	            		//check the contain and the length
    	            		if(new String(jTextField2.getPassword()).trim().length() > 3 && new String(jTextField5.getPassword()).trim().length() > 3
    	            			&& new String(jTextField2.getPassword()).trim().matches("[a-z0-9]+") && new String(jTextField5.getPassword()).trim().matches("[a-z0-9]+")){
    	            			
    	            			//for id_account
    	            			result = connection.getData("SHOW TABLE STATUS LIKE 'ACCOUNTS'");
    	            			
    	                    	String format = "yyyy-MM-dd";
    	                    	//date of today
    	                    	SimpleDateFormat formater = new SimpleDateFormat(format);
    	                    	Date date = new Date();
    	                    	
    	            			while(result.next()){
    	            				Useful use = new Useful();
            	            		connection.putData("INSERT INTO ACCOUNTS VALUES('"+result.getString("Auto_increment")+"','"+jTextField1.getText().trim()+"','"+use.sha1(new String(jTextField2.getPassword()).trim())+"','"+formater.format(date)+"','"+formater.format(date)+"',0)");
            	            		
            	            		JOptionPane.showMessageDialog(null, "User added successfully.", "Add User", JOptionPane.INFORMATION_MESSAGE);
            	            		jTextField1.setText("");
            	            		jTextField2.setText("");
            	            		jTextField5.setText("");

    	            			}

    	            		}
    	            		else{
            	                JOptionPane.showMessageDialog(null, "Sorry the password should have at least 4 characters. It only can contain letters and numbers.", "Invalid Password", JOptionPane.WARNING_MESSAGE);
            	                jTextField2.setText("");
            	                jTextField5.setText("");
            	            }
    	            		
    	            	}
    	            	else{
        	                JOptionPane.showMessageDialog(null, "Sorry the password and the confirmation are different.", "Invalid Password", JOptionPane.WARNING_MESSAGE);
        	                jTextField2.setText("");
        	                jTextField5.setText("");
        	            }
    	            	
    	            }
    	            else{
    			    	JOptionPane.showMessageDialog(null, "This username already exists. Please choose another one.", "Invalid Username", JOptionPane.WARNING_MESSAGE);
    			    	jTextField1.setText("");
    			    }


    	        } catch (Exception e) {
    	            JOptionPane.showMessageDialog(null, "Unable to connect to MySQL database.\n" + e, "Database Error", JOptionPane.WARNING_MESSAGE);
    	        }
				
			}
			else{
		    	JOptionPane.showMessageDialog(null, "Please confirm your password", "Invalid Confirmation", JOptionPane.WARNING_MESSAGE);
		    }
		}
		else{
	    	JOptionPane.showMessageDialog(null, "Please enter a password", "Invalid Password", JOptionPane.WARNING_MESSAGE);
	    }	
	}
	else{
    	JOptionPane.showMessageDialog(null, "Please enter a username", "Invalid Username", JOptionPane.WARNING_MESSAGE);
    }


}


    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPasswordField jTextField2;
    private javax.swing.JPasswordField jTextField5;
    private javax.swing.JTextPane jTextPane_date_description;
    // End of variables declaration

}
