/*
 * AlterType.java
 *
 * Created on 25 mars 2009, 16:10
 */

package cinemacontroller.gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.colorchooser.AbstractColorChooserPanel;

import databasecontroller.MySqlController;
import databasecontroller.TextLimiter;

/**
 *
 * @author  Frédéric
 */
public class AlterType extends javax.swing.JFrame {

	private static final long serialVersionUID = 0L;
	private Color newColor;
	private ArrayList<String> colorRGB = new ArrayList<String>();
    /** Creates new form AlterType */
    public AlterType() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane_date_description = new javax.swing.JTextPane();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        modelComboBox1 = new javax.swing.DefaultComboBoxModel();
        jTextField2 = new javax.swing.JTextField();
        colorChooser= new javax.swing.JColorChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alter Type - Multiplex Manager");
        setIconImage(getToolkit().getImage(getClass().getResource("/cinemacontroller/gui/icons/dvd_add.png")));

        jPanel2.setBackground(new java.awt.Color(24, 24, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alter Type");

        jScrollPane3.setBorder(null);

        jTextPane_date_description.setBackground(new java.awt.Color(24, 24, 24));
        jTextPane_date_description.setEditable(false);
        jTextPane_date_description.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane_date_description.setText("You can alter a type that already exists by choosing it in the list. Then, fill in the box to the right with the new type and change the color if you want to. ");
        jScrollPane3.setViewportView(jTextPane_date_description);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTextField1.setDocument(new TextLimiter(40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("Type");

        jButton3.setText("Change Color");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("Current Type");

        MySqlController connection;
        ResultSet result;
        
		modelComboBox1 = new DefaultComboBoxModel();
		
        jComboBox1 = new javax.swing.JComboBox(modelComboBox1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	jComboBox1ActionPerformed(evt);
            }
        });
        
        
        
		try {
			
			connection = MySqlController.getInstance();
			result= connection.getData("SELECT * FROM TYPES ORDER BY NAME");
			jComboBox1.addItem("");
			colorRGB.add("");
			while (result.next()) {
				jComboBox1.addItem(result.getString(2));
				
				//store all colors in an arrayList
				colorRGB.add(result.getString(3));
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
        jTextField2.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, 0, 294, Short.MAX_VALUE)
                        .addComponent(jTextField1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	if(this.jComboBox1.getSelectedItem() != this.jComboBox1.getItemAt(0)){
    		
    		if(!jTextField1.getText().trim().isEmpty()){
    			
    			boolean exist = false;

    			//check if the type written doesn't exist
    			try {
        			MySqlController connection = MySqlController.getInstance();

        			ResultSet r = connection.getData("SELECT NAME FROM TYPES WHERE NAME='"+jTextField1.getText().toLowerCase().trim()+"'");

        			while(r.next()){
        				if(r.getString(1).toLowerCase().equals(jTextField1.getText().toLowerCase().trim())){
        					exist = true;
        					JOptionPane.showMessageDialog(null, "This name already exists.", "Invalid Type", JOptionPane.WARNING_MESSAGE);
        					jTextField1.setText("");
        					break;
        				}
        				
        			}

        			//if the type doesn't exist, we update it into the database (with the new color)
        			if(!exist){
            			
            				
            				if(newColor != null){
            					connection.putData("UPDATE TYPES SET NAME='"+jTextField1.getText().trim()+"', COLOR_RGB='"+cutColor()+"' WHERE NAME='"+jComboBox1.getSelectedItem()+"'");
            				}
            				else{
            					connection.putData("UPDATE TYPES SET NAME='"+jTextField1.getText().trim()+"' WHERE NAME='"+jComboBox1.getSelectedItem()+"'");
            				}
                			
                			JOptionPane.showMessageDialog(null, "Type updated successfully.", "Type", JOptionPane.INFORMATION_MESSAGE);
                			jTextField1.setText("");
                			jComboBox1.setSelectedIndex(0);
            		
        			}
    	
        		} catch (SQLException e) {
        			e.printStackTrace();
        		}
    			
    		}
    		else{
            	JOptionPane.showMessageDialog(null, "Please write the new type.", "Invalid Type", JOptionPane.WARNING_MESSAGE);
            }
    	}
    	else{
        	JOptionPane.showMessageDialog(null, "Please choose a type.", "Invalid Type", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	this.dispose();
    }
    
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	if(this.jComboBox1.getSelectedItem() != this.jComboBox1.getItemAt(0)){

    		String color = colorRGB.get(jComboBox1.getSelectedIndex());

    		String red = color.substring(0, color.indexOf(","));
    		color = color.substring(color.indexOf(",")+1, color.length());
    		String green = color.substring(0, color.indexOf(","));
    		color = color.substring(color.indexOf(",")+1, color.length());
    		String blue = color;

    		jTextField2.setBackground(new java.awt.Color(new Integer(red), new Integer(green), new Integer(blue)));
    		
    	}
    	
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
    	
        final JLabel previewLabel = new JLabel();
        
        ActionListener okListener = new ActionListener() {
            // Called when user clicks ok
            public void actionPerformed(ActionEvent evt) {

                // Get selected color
                newColor = colorChooser.getColor();
            }
        };
        
        colorChooser.setPreviewPanel(previewLabel);

        AbstractColorChooserPanel [] panel = colorChooser.getChooserPanels ();

        /*colorChooser.removeChooserPanel (panel [1]);
        colorChooser.removeChooserPanel (panel [2]);*/

        JDialog d = colorChooser.createDialog(null,"Choose a color - Multiplex Manager",true,colorChooser,okListener,null);
        
        d.setIconImage(getToolkit().getImage(getClass().getResource("/cinemacontroller/gui/icons/dvd_add.png")));
        d.setVisible(true);

    }
    
    public String cutColor() {
    	
    	String color = newColor.toString().substring(newColor.toString().indexOf("[")+1, newColor.toString().length()-1);
    	color = color.replace("r=", "").replace("g=", "").replace("b=", "").trim();
    	
    	return color;
    	
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.DefaultComboBoxModel modelComboBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane_date_description;
    // End of variables declaration

}
