/*
 * AlterDistributor.java
 *
 * Created on 25 mars 2009, 16:53
 */

package cinemacontroller.gui;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import databasecontroller.MySqlController;
import usefulmethods.TextLimiter;

/**
 *
 * @author  Frédéric
 */
public class AlterDistributor extends javax.swing.JFrame {

	private static final long serialVersionUID = 0L;
    /** Creates new form AlterDistributor */
    public AlterDistributor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane_date_description = new javax.swing.JTextPane();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        modelComboBox1 = new javax.swing.DefaultComboBoxModel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alter Distributor - Multiplex Manager");
        setIconImage(getToolkit().getImage(getClass().getResource("/cinemacontroller/gui/icons/dvd_add.png")));

        jPanel2.setBackground(new java.awt.Color(24, 24, 24));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Alter Distributor");

        jScrollPane3.setBorder(null);

        jTextPane_date_description.setBackground(new java.awt.Color(24, 24, 24));
        jTextPane_date_description.setEditable(false);
        jTextPane_date_description.setForeground(new java.awt.Color(255, 255, 255));
        jTextPane_date_description.setText("You can alter a distributor that already exists by choosing it in the list. Then, fill in the box to the right with the new distributor. ");
        jScrollPane3.setViewportView(jTextPane_date_description);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jTextField1.setDocument(new TextLimiter(60));
        
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel11.setText("Current Distributor");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("Distributor");

        MySqlController connection;
        ResultSet result;
        
		modelComboBox1 = new DefaultComboBoxModel();
		
        jComboBox1 = new javax.swing.JComboBox(modelComboBox1);
        
		try {
			connection = MySqlController.getInstance();
			result= connection.getData("SELECT NAME FROM DISTRIBUTORS ORDER BY NAME");
			jComboBox1.addItem("");
			while (result.next()) {
				jComboBox1.addItem(result.getString(1));
			}
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, 0, 294, Short.MAX_VALUE)
                    .addComponent(jTextField1))
                .addGap(15, 15, 15)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	if(this.jComboBox1.getSelectedItem() != this.jComboBox1.getItemAt(0)){
    		
    		if(!jTextField1.getText().trim().isEmpty()){
    			
    			boolean exist = false;

    			//check if the distributor written doesn't exist
    			try {
        			MySqlController connection = MySqlController.getInstance();

        			ResultSet r = connection.getData("SELECT NAME FROM DISTRIBUTORS WHERE NAME='"+jTextField1.getText().toLowerCase().trim()+"'");

        			while(r.next()){
        				if(r.getString(1).toLowerCase().equals(jTextField1.getText().toLowerCase().trim())){
        					exist = true;
        					JOptionPane.showMessageDialog(null, "This name already exists.", "Invalid Distributor", JOptionPane.WARNING_MESSAGE);
        					jTextField1.setText("");
        					break;
        				}
        				
        			}

        			//if the distributor doesn't exist, we update it into the database
        			if(!exist){
            			
            			connection.putData("UPDATE DISTRIBUTORS SET NAME='"+jTextField1.getText().trim()+"' WHERE NAME='"+jComboBox1.getSelectedItem()+"'");
                		JOptionPane.showMessageDialog(null, "Distributor updated successfully.", "Distributor", JOptionPane.INFORMATION_MESSAGE);
                		this.dispose();
        			}
    	
        		} catch (SQLException e) {
        			e.printStackTrace();
        		}
    			
    		}
    		else{
            	JOptionPane.showMessageDialog(null, "Please write the new distributor.", "Invalid Distributor", JOptionPane.WARNING_MESSAGE);
            }
    	}
    	else{
        	JOptionPane.showMessageDialog(null, "Please choose a distributor.", "Invalid Distributor", JOptionPane.WARNING_MESSAGE);
        }

    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    	
    	this.dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.DefaultComboBoxModel modelComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextPane jTextPane_date_description;
    // End of variables declaration

}
