/*
 * MainW.java
 *
 * Created on 28 mars 2009, 23:51
 */

package cinemacontroller.gui;

import java.awt.Component;
import java.sql.ResultSet;
import java.sql.Time;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Iterator;

import javax.swing.JComboBox;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

import usefulmethods.Useful;

import cinemacontroller.gui.timetablecontrol.TimetableController;
import cinemacontroller.gui.timetablecontrol.TimetableGenerating;
import cinemacontroller.gui.timetablecontrol.TimetableRunning;
import cinemacontroller.historicalcontroller.ImportController;
import cinemacontroller.rotationalcontroller.AutomaticRotation;
import cinemacontroller.screencontroller.ScreenManager;
import databasecontroller.MySqlController;

/**
 *
 * @author  Frédéric
 */
public class MainWindow extends javax.swing.JFrame {

	private static final long serialVersionUID = -3688656990364226359L;
    private String login ;
    private Useful use ;
    private ArrayList<JTextField> shows = new ArrayList<JTextField>();
    private TimetableController timetableD = new TimetableController();
    
    /** Creates new form MainW */
    public MainWindow(String login) {

        // Curent login
        this.login = login;
        use = new Useful();
        // Creates all the default controls.
        this.initComponents();

        // Center align the login window
        this.setLocationRelativeTo(null);
        this.setVisible(true);
  
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        timetable = new javax.swing.JButton();
        timetable2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        statistics = new javax.swing.JButton();
        historical = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        viewFilms = new javax.swing.JButton();
        options = new javax.swing.JButton();
        user = new javax.swing.JButton();
        comboDay = new javax.swing.JComboBox();
        comboWeek = new javax.swing.JComboBox();
        display = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(login+" - Multiplex Manager");
        setIconImage(getToolkit().getImage(getClass().getResource("/cinemacontroller/gui/icons/images.png")));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        timetable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemacontroller/gui/icons/timetable.png"))); // NOI18N
        timetable.setFocusable(false);
        timetable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        timetable.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        timetable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetableActionPerformed(evt);
            }
        });
        jToolBar1.add(timetable);

        timetable2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemacontroller/gui/icons/timetable.png"))); // NOI18N
        timetable2.setFocusable(false);
        timetable2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        timetable2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        timetable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timetable2ActionPerformed(evt);
            }
        });
        jToolBar1.add(timetable2);
        jToolBar1.add(jSeparator2);

        statistics.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemacontroller/gui/icons/chart_pie.png"))); // NOI18N
        statistics.setToolTipText("View statistical data.");
        statistics.setFocusable(false);
        statistics.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        statistics.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        statistics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statisticsActionPerformed(evt);
            }
        });
        jToolBar1.add(statistics);

        historical.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemacontroller/gui/icons/hourglass.png"))); // NOI18N
        historical.setFocusable(false);
        historical.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        historical.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        historical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historicalActionPerformed(evt);
            }
        });
        jToolBar1.add(historical);
        jToolBar1.add(jSeparator3);

        viewFilms.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemacontroller/gui/icons/images.png"))); // NOI18N
        viewFilms.setToolTipText("Open the film manager to browse, add and edit films stored in the database.");
        viewFilms.setFocusable(false);
        viewFilms.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        viewFilms.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        viewFilms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFilmsActionPerformed(evt);
            }
        });
        jToolBar1.add(viewFilms);

        options.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemacontroller/gui/icons/options.png"))); // NOI18N
        options.setFocusable(false);
        options.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        options.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                optionsActionPerformed(evt);
            }
        });
        jToolBar1.add(options);

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinemacontroller/gui/icons/user.png"))); // NOI18N
        user.setToolTipText("Add or change user's information.");
        user.setFocusable(false);
        user.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jToolBar1.add(user);

        comboDay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Thursday", "Friday", "Saturday", "Sunday", "Monday", "Tuesday", "Wednesday" }));
        comboDay.setBorder(null);
        
		Iterator it = timetableD.fillComboBoxWeekRotation().iterator();
		while(it.hasNext()){
			comboWeek.addItem(it.next().toString());
		}

        comboWeek.setBorder(null);

        display.setText("Display");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        jLabel1.setText("Day");

        jLabel2.setText("Week");

        jTabbedPane1.addTab("Summary", jTabbedPane2);
        jTabbedPane1.addTab("Actions", jTabbedPane3);

        jLabel3.setText("Idle.");

        jLabel4.setText("14:00");

        jLabel5.setText("14:30");

        jLabel6.setText("15:00");

        jLabel7.setText("15:30");

        jLabel8.setText("16:00");

        jLabel9.setText("16:30");

        jLabel10.setText("17:00");

        jLabel11.setText("17:30");

        jLabel12.setText("18:00");

        jLabel13.setText("18:30");

        jLabel14.setText("19:00");

        jLabel15.setText("19:30");

        jLabel16.setText("20:00");

        jLabel17.setText("20:30");

        jLabel18.setText("21:00");

        jLabel19.setText("21:30");

        jLabel20.setText("22:00");

        jLabel21.setText("22:30");

        jLabel22.setText("23:00");

        jLabel23.setText("23:30");

        jLabel24.setText("00:00");

        jLabel25.setText("00:30");

        jLabel26.setText("01:00");

        jLabel27.setText("01:30");

        jLabel28.setText("02:00");

       //JTextField jTextField1 = new JTextField();
       //jTextField1 .setText("jTextField1");
        //jTextField1.setBounds(10, 40, 59, 170);
        //jLayeredPane1.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        

        displayJtable();
        
        jScrollPane1.setBounds(-10, 2, 1060, 560);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenu7.setText("File");

        jMenuItem23.setText("Exit");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem23);

        jMenuBar2.add(jMenu7);

        jMenu11.setText("New");

        jMenuItem13.setText("Film");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem13);

        jMenuItem14.setText("Type");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem14);

        jMenuItem15.setText("Distributor");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem15);

        jMenuItem16.setText("Expected Audience");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem16);

        jMenuBar2.add(jMenu11);

        jMenu13.setText("Alter");

        jMenuItem17.setText("Film");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem17);

        jMenuItem18.setText("Type");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem18);

        jMenuItem25.setText("BBFC");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem25);

        jMenuItem19.setText("Distributor");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem19);

        jMenuItem20.setText("Expected Audience");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem20);

        jMenuBar2.add(jMenu13);

        jMenu14.setText("Historical");

        jMenuItem22.setText("Import");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu14.add(jMenuItem22);

        jMenuBar2.add(jMenu14);

        jMenu12.setText("Help");

        jMenuItem24.setText("About");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem24);

        jMenuBar2.add(jMenu12);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboDay, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(comboWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(display))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel26)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1041, Short.MAX_VALUE))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(display)
                            .addComponent(jLabel2)
                            .addComponent(comboWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {
    	this.dispose();
    	}

    	private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {
    	new CreateNewFilm();
    	}

    	private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {
    	new CreateNewType();
    	}

    	private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {
    	new CreateNewDistributor();
    	}

    	private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {
    	new CreateNewExpectedAudience();
    	}

    	private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {

    	}

    	private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {
    	new AlterType();
    	}

    	private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {
    	new AlterDistributor();
    	}

    	private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {
    	new AlterExpectedAudience();
    	}

    	private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {
//    	 TODO add your handling code here:
    	}

    	private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {
   	 		new ImportController();
    	}

    	private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {
    	new AboutProgram(this);
    	}

    	private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {
        	new AlterBbfc();
        }

    	private void timetableActionPerformed(java.awt.event.ActionEvent evt) {
    		new ScreenManager(0);
    	}

    	private void timetable2ActionPerformed(java.awt.event.ActionEvent evt) {
    		new ScreenManager(1);
    	}

    	private void statisticsActionPerformed(java.awt.event.ActionEvent evt) {
//    	 TODO add your handling code here:
    	}

    	private void historicalActionPerformed(java.awt.event.ActionEvent evt) {
//    	 TODO add your handling code here:
    	}

    	private void viewFilmsActionPerformed(java.awt.event.ActionEvent evt) {
    	new FilmList(this);
    	}

    	private void viewScreensActionPerformed(java.awt.event.ActionEvent evt) {
//    	 TODO add your handling code here:
    	}

    	private void userActionPerformed(java.awt.event.ActionEvent evt) {
    	new UserList(this);
    	}
    	
    	private void optionsActionPerformed(java.awt.event.ActionEvent evt) {

        	}         

private void displayActionPerformed(java.awt.event.ActionEvent evt) {   
	
	timetableD.goNewWeek();

	int day = comboDay.getSelectedIndex();
	int index = comboWeek.getSelectedIndex();

	String temp = (String)comboWeek.getItemAt(index);
	temp = temp.substring(0,temp.indexOf(" ")).trim();

	Calendar beginSelectedWeek = use.toCalendar(temp);
	beginSelectedWeek = use.changeDate(beginSelectedWeek, day);

	try {

    	MySqlController connection = MySqlController.getInstance();
    	//System.out.println("SELECT * FROM OPERATING_HOUR WHERE BEGIN_DATE<'"+use.calendarToString(beginSelectedWeek)+"' && END_DATE IS NULL");
    	ResultSet r4 = connection.getData("SELECT * FROM OPERATING_HOUR WHERE BEGIN_DATE<'"+use.calendarToString(beginSelectedWeek)+"' && END_DATE IS NULL");
    
    	String pausedTime = "";
    	String startHour = "";
    	
    	if(r4.next()){
    		
    		if(day == 1 || day == 2 || day == 3){
    			pausedTime = r4.getString(6);
    			startHour = r4.getString(5);
    		}
    		else{
    			pausedTime = r4.getString(3);
    			startHour = r4.getString(2);
    		}
    		
    	}

    	ResultSet r2 = connection.getData("SELECT * FROM TIMETABLES WHERE DAY='"+use.calendarToString(beginSelectedWeek)+"'");
    	if(!r2.next()){
    		//enableAllComponents();
    		JOptionPane.showMessageDialog(null, "No shows scheduled for this day.", "Display Timetable", JOptionPane.WARNING_MESSAGE);
    	}
    	else{
        	ResultSet r = connection.getData("SELECT * FROM SCREENS ORDER BY ID_SCREEN");
        	
        	while(r.next()){
        		//System.out.println("SELECT * FROM TIMETABLES WHERE DAY='"+use.calendarToString(beginSelectedWeek)+"' AND ID_SCREEN='"+r.getInt(1)+"'");
        		ResultSet r1 = connection.getData("SELECT * FROM TIMETABLES WHERE DAY='"+use.calendarToString(beginSelectedWeek)+"' AND ID_SCREEN='"+r.getInt(1)+"'");
        		
        		if(r1.next()){
        			int idMovie = r1.getInt(2);
        			
        			if(idMovie != 0){
            			int nbShows = 0;
            			nbShows = use.numberShows(r1.getString(2), beginSelectedWeek);
            			
            			ResultSet r3 = connection.getData("SELECT * FROM MOVIES WHERE ID_MOVIE='"+idMovie+"'");
            			
            			if(r3.next()){
            				String runningTime = r3.getString(10);

            				int hour = use.getHour(runningTime);
            				int mins = use.getMins(runningTime);

            				timetableD.addOpenScreen(nbShows,hour,mins,idMovie,r1.getInt(4),r1.getInt(5),pausedTime,startHour);
            				
            			}
        			}
        			else{
        				timetableD.addClosedScreen();
        			}
        		}
        		timetableD.goNextScreen();
        	}
        	
        	JOptionPane.showMessageDialog(null, "The timetable has been generated.", "Display timetable", JOptionPane.INFORMATION_MESSAGE);

    	}
    	

    } catch (Exception e) {
    	JOptionPane.showMessageDialog(null, "Unable to connect to MySQL database.\n" + e, "Database Error", JOptionPane.WARNING_MESSAGE);
    }
    
    for(int i=0;i<timetableD.getShows().size();i++){
		jLayeredPane1.add(timetableD.getShows().get(i), javax.swing.JLayeredPane.DRAG_LAYER);
	}
    
    displayJtable();

}     

public void displayJtable(){
	
    jTable1.getTableHeader().setReorderingAllowed(false);
    jTable1.getTableHeader().setResizingAllowed(false);
    jTable1.setEnabled(false);
    jTable1.setShowHorizontalLines(false);
    //jTable1.setBorder(new Border());
    jTable1.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null},
            {null, null, null, null}
        },
        new String [] {
            "Screen 1", "Screen 2", "Screen 3", "Screen 4", "Screen 5", "Screen 6", "Screen 7", "Screen 8", "Screen 9", "Screen 10", "Screen 11", "Screen 12"
        }
    ));
    jScrollPane1.setViewportView(jTable1);

}




    // Variables declaration - do not modify
    private javax.swing.JComboBox comboDay;
    private javax.swing.JComboBox comboWeek;
    private javax.swing.JButton display;
    private javax.swing.JButton historical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton options;
    private javax.swing.JButton statistics;
    private javax.swing.JButton timetable;
    private javax.swing.JButton timetable2;
    private javax.swing.JButton user;
    private javax.swing.JButton viewFilms;
    // End of variables declaration
    
	public String getLogin() {
		return login;
	}
	
	public JComboBox getComboDay() {
		return comboDay;
	}
	
	public JComboBox getComboWeek() {
		return comboWeek;
	}
	public JLayeredPane getLayeredPane() {
		return jLayeredPane1;
	}

}
